///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MenuRootEntity {
/*
{
  "menuIcon": "https://ik.imagekit.io/guoguodad/mall/home/supermarket.png?updatedAt=1691716657143",
  "menuName": "超市",
  "menuCode": "m01",
  "h5url": "https://prodev.m.jd.com/mall/active/3xhqjGH1wMz5FaMgrfYhR22sFvqz/index.html"
} 
*/

  String? menuIcon;
  String? menuName;
  String? menuCode;
  String? h5url;
  Map<String, dynamic> __origJson = {};

  MenuRootEntity({
    this.menuIcon,
    this.menuName,
    this.menuCode,
    this.h5url,
  });
  MenuRootEntity.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    menuIcon = json['menuIcon']?.toString();
    menuName = json['menuName']?.toString();
    menuCode = json['menuCode']?.toString();
    h5url = json['h5url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['menuIcon'] = menuIcon;
    data['menuName'] = menuName;
    data['menuCode'] = menuCode;
    data['h5url'] = h5url;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
